# Generated by Django 5.1.6 on 2025-02-22 11:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_alter_match_unique_together_alter_match_user1_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='matchpair',
            name='status',
            field=models.CharField(choices=[('pending', 'Függőben'), ('matched', 'Egyezés'), ('unmatched', 'Megszakítva')], default='matched', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='liked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='match',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchpair',
            name='user1',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs_as_user1', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='matchpair',
            name='user2',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_pairs_as_user2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='match',
            unique_together={('user1', 'user2')},
        ),
        migrations.AlterUniqueTogether(
            name='matchpair',
            unique_together={('user1', 'user2')},
        ),
    ]
