"""
Django settings for fatal_love project.

Generated by 'django-admin startproject' using Django 5.1.6.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# ⚠ FONTOS: Titkos kulcs elrejtése környezeti változóban
SECRET_KEY = os.getenv("SECRET_KEY", "django-insecure-*o%a7lkye+armp6zvw-^y3tx!l*p1!-2+=#g=4)^=@%of4#q*!")

DEBUG = True

ALLOWED_HOSTS = ["localhost", "127.0.0.1"]


#Új sorok
# ✅ Django REST keretrendszer konfiguráció
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    )
}

AUTH_USER_MODEL = 'users.CustomUser'

# ✅ Media fájlok kezelése
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# ✅ CORS beállítások (React frontend támogatása)
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://127.0.0.1:5173",
]

CORS_ALLOW_CREDENTIALS = True

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]

# ✅ WebSocket támogatás és Redis beállítás
ASGI_APPLICATION = "fatal_love.asgi.application"

CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer"
    }
}

# ✅ Email küldés beállítások
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv("EMAIL_USER", "YOUR_EMAIL@gmail.com")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_PASSWORD", "YOUR_APP_PASSWORD")

# ✅ Caching (Redis gyorsítótár)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Logging beállítások optimalizálása
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
            'level': 'ERROR',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
        'messaging': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': True,
        },
    },
}

# Application definition

# ✅ Telepített alkalmazások
INSTALLED_APPS = [
    'daphne',  # Ennek kell lennie az első helyen
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles', # 🔥 Csak a daphne után jöhet!
    'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',    
    'channels',
    'channels_redis',  # Redis támogatás
    'users',
    'profiles',
    'matches',
    'messaging',
]

# ✅ Middleware beállítások
MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # WhiteNoise middleware
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'fatal_love.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR.parent / 'frontend' / 'dist'],  # React build mappa
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]
# ✅ ASGI és WSGI alkalmazások
WSGI_APPLICATION = 'fatal_love.wsgi.application'

# ✅ Adatbázis beállítások (alapértelmezett SQLite, de PostgreSQL-re is átállítható)
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}


# ✅ Jelszó ellenőrzési szabályok
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# ✅ Nemzetközi beállítások
LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_TZ = True

# ✅ Statikus fájlok kezelése
STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Django admin és egyéb statikus fájlok helyének beállítása
STATICFILES_DIRS = [
    BASE_DIR / "static",  # Ha van egy `static/` mappa a projekt gyökérkönyvtárában
    BASE_DIR.parent / "frontend" / "dist",  # React build mappa
]

# Új beállítás a React routerhez
WHITENOISE_INDEX_FILE = True
WHITENOISE_ROOT = BASE_DIR.parent / "frontend" / "dist"

# ✅ Alapértelmezett elsődleges kulcs beállítása
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

