# Generated by Django 5.1.6 on 2025-03-01 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('F', 'Nő'), ('M', 'Férfi'), ('O', 'Egyéb')], default='O', max_length=1),
        ),
    ]
